/**
 * Ids (`<title>/<export name>`) of the stories every screen state must have, from
 * specs/001-shopping-lists/contracts/ui-validation.md#required-stories. Each story phase
 * adds its ids here; stories.test.tsx fails for an id that no story has.
 */
export const requiredStories: readonly string[] = [
  'Components/LoadingState/Default',
  'Components/EmptyState/WithAction',
  'Components/EmptyState/WithoutAction',
  'Components/ErrorState/Default',
  'Screens/Startup/Error',
  'Screens/Startup/UpdateRequired',
  'Screens/Crash/Error',
  // User Story 1
  'Components/ListItemRow/NotInCart',
  'Components/ListItemRow/InCart',
  'Components/ListItemRow/WithQuantity',
  'Components/ListItemRow/LongName',
  'Components/NoticeSnackbar/WriteFailed',
  'Components/NoticeSnackbar/StorageFull',
  'Components/NoticeSnackbar/ArticleDeletedElsewhere',
  'Components/NoticeSnackbar/ItemRemovedElsewhere',
  'Screens/CurrentList/Loading',
  'Screens/CurrentList/Error',
  'Screens/CurrentList/Empty',
  'Screens/CurrentList/Success',
  'Screens/CurrentList/AllInCart',
  'Dialogs/FinishShoppingDialog/Default',
  // User Story 2
  'Components/ArticleRow/Default',
  'Components/ArticleRow/AlreadyOnList',
  'Components/QuantityFields/Empty',
  'Components/QuantityFields/Filled',
  'Components/QuantityFields/WithError',
  'Components/NameField/Empty',
  'Components/NameField/WithError',
  'Components/UndoSnackbar/RemovedItem',
  'Screens/AddArticles/Loading',
  'Screens/AddArticles/Error',
  'Screens/AddArticles/NoQuery',
  'Screens/AddArticles/SearchMatches',
  'Screens/AddArticles/SearchNoMatch',
  'Screens/CreateArticle/Empty',
  'Screens/CreateArticle/NameAlreadyUsed',
  'Screens/EditArticle/Default',
  'Screens/EditArticle/NameAlreadyUsed',
  'Screens/EditArticle/NameRequired',
  'Dialogs/QuantityDialog/Add',
  'Dialogs/QuantityDialog/Edit',
  'Dialogs/QuantityDialog/AlreadyOnList',
  'Dialogs/QuantityDialog/InvalidAmount',
  // User Story 3
  'Screens/Lists/Loading',
  'Screens/Lists/Error',
  'Screens/Lists/Success',
  'Dialogs/CreateListDialog/Default',
  'Dialogs/CreateListDialog/NameAlreadyUsed',
  'Dialogs/CreateCategoryDialog/Default',
  'Dialogs/CreateCategoryDialog/NameAlreadyUsed',
  // 002 Manage articles
  'Components/CategoryPicker/Default',
  'Components/CategoryPicker/NewCategorySelected',
  'Components/UndoSnackbar/DeletedArticle',
  'Dialogs/DeleteArticleDialog/NoList',
  'Dialogs/DeleteArticleDialog/OneList',
  'Dialogs/DeleteArticleDialog/SeveralLists',
  // 003 Server sync
  'Screens/Settings/NotConnected',
  'Screens/Settings/Connected',
  // User Story 4
  'Screens/Settings/DevicesLoading',
  'Screens/Settings/DevicesError',
  'Screens/Settings/DevicesOffline',
  'Dialogs/PairingCodeDialog/Code',
  'Dialogs/PairingCodeDialog/Offline',
  'Dialogs/RevokeDeviceDialog/Default',
  'Dialogs/DisconnectDialog/Default',
  'Dialogs/RenameDeviceDialog/Default',
  'Dialogs/ChangeServerUrlDialog/Default',
  'Dialogs/ChangeServerUrlDialog/ServerMismatch',
  'Screens/ConnectServer/Default',
  'Screens/ConnectServer/ServerUnreachable',
  'Screens/ConnectServer/InvalidCode',
  'Screens/ConnectServer/UntrustedServer',
  'Screens/ConnectServer/TooManyAttempts',
  'Components/SyncStatusBar/Saved',
  'Components/SyncStatusBar/Waiting',
  'Components/SyncStatusBar/Sending',
  'Components/SyncStatusBar/Failed',
  'Components/SyncStatusBar/DisconnectedByServer',
  'Components/SyncStatusBar/UpdateRequired',
  'Screens/CurrentList/WithSyncStatus',
];
