// storybook.requires.ts is generated by Storybook when Metro starts with STORYBOOK_ENABLED.
// eslint-disable-next-line import/no-unresolved
import { view } from './storybook.requires';

const StorybookUIRoot = view.getStorybookUI({});

export default StorybookUIRoot;
